### ISSUE TITLE
Should lint on `package::function` pattern

### ISSUE THREAD

**Issue by radbasa** [Appsilon/box.linters#104]
Because `box` is being used, it is not advisable to directly call a package.

Disallow `package::function()` except `box::use()`.

Maybe have a whitelist for allowed `package::function()`s

**Comment by mhtorp** [comment]
First I want to say thank you for this great package. I have really been missing using something like `lintr::object_usage_linter` in a box context!

However, I would really like to have an escape hatch for allowing the use of namespace prefix on function calls, since it integrates better with the R language server when there are multiple packages are exporting a function with the same name.

Here is an example of `dplyr::filter` clashing with `stats::filter`:

![image](https://github.com/Appsilon/box.linters/assets/20072569/39945319-7413-4932-9236-922f4f964402)

As you can see, `filter` is imported from `dplyr` using `box` on line 4. However, the documentation in the hover box is from `stats::filter`. This is also the case when using the language server for function argument completion:

![image](https://github.com/Appsilon/box.linters/assets/20072569/230d70e2-f9e8-4224-b63d-a517f8d46fbc)

If I on the other hand explicitly namespace `filter`, i.e. use `dplyr::filter`, the documentation works as expected:
![image](https://github.com/Appsilon/box.linters/assets/20072569/96fa74c2-035a-4eed-8d55-839a0d448280)
![image](https://github.com/Appsilon/box.linters/assets/20072569/a30b28d4-1f4e-4b0d-9af9-841bc4578f5b)


I hope this is enough motivation for having a flag in `box.linters::box_usage_linter()` to allow explicit namespace prefixing of functions. What are your thoughts on this?

**Comment by radbasa** [comment]
@mhtorp Thank you for your feedback!

When using `{box}`, using `package::function()` is not advisable because it bypasses the packages loaded by `{box}` into the environment. We are aware that this breaks the very useful VS Code auto-complete and on-hover help. This, however, is a shortcoming of the language server for R. The language server does not see packages loaded with `box::use()` like it does with those loaded by `library()` or `require()`. As we also use VS Code and we wish language server understood `{box}` modules, we are looking into providing `{box}` module support to the R language server.

Rest assured, if and when we add the linter blocking `package::function()`, it will be a separate linter function and can be disabled by setting it's entry to `NULL`.
